TrabajoFinal/TrabajoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.base, name= 'base'),
    path('nosotros/', views.nosotros, name = 'nosotros'),
    #path("accounts/login/", views.login, name= "login"),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', auth.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),
    path('vernoticias/', include('apps.categorias.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

TrabajoFinal/apps/categorias/urls.py
from django.urls import path
from . import views

app_name = 'categorias'
urlpatterns = [
    path('categoria/', views.RedactarNoticia.as_view(), name='ver'),
    path('Listarnoticia/', views.Listar_Noticia.as_view(), name='noticias'),
    path('articulo/<int:pk>/', views.DetalleArticulo.as_view(), name='detallearticulo'),
    path('articulo/<int:pk>/comentario/', views.ComentarioViews.as_view(), name='nuevocoment'), 
    path('articulo/editar/<int:pk>/', views.EditarRedaccion.as_view(), name='editar'),
    path('articulo/<int:pk>/eliminar', views.EliminarRedaccion.as_view(), name='eliminar'),

]

TrabajoFinal/apps/usuario/urls.py
from django.urls import path
from . import views
from .views import RegistroUsuario

app_name = 'usuario'
urlpatterns = [
#    path("Newnoticia/", views.noticia , name= "nueva_noticia"),
    path("registro/", RegistroUsuario.as_view(), name= "registrar"),
]

TrabajoFinal/apps/categorias/models.py
from django.db import models
from django.db.models.fields import CharField, DateTimeField
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    nombre = CharField(max_length=50)

    def __str__(self):
        return (self.nombre)

    def get_absolute_url(self):
        return reverse('base')

class Redaccion(models.Model):
    titulo = models.CharField(max_length=100)
    texto = models.TextField() 
    fecha = models.DateField(default=timezone.now)
    categoria = models.CharField(max_length=255, default='coding')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    
    class Meta:
        ordering = ['-fecha']

    def __str__(self):
        return self.titulo 


class Comentario(models.Model):
    post = models.ForeignKey(Redaccion, related_name='comentarios', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255)
    cuerpo = models.TextField()
    fecha_comentario = DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

TrabajoFinal/apps/usuario/models.py
from django.db import models  

TrabajoFinal/apps/categorias/forms.py
from django import forms
from .models import Comentario, Redaccion


choices = [('Internacional', 'Internacional'), ('Policiales','Policiales'), ('Nacionales','Nacionales'), ('Deportes','Deportes')]

class Formulario_Alta_Redaccion(forms.ModelForm):
    class Meta:
        model = Redaccion
        fields = ['titulo', 'texto', 'fecha', 'autor', 'categoria']

        widgets = {
            'titulo': forms.TextInput(attrs={'class':'form-control'}),
            'texto': forms.Textarea(attrs={'class':'form-control'}),
            'fecha': forms.SelectDateWidget(attrs={'class':'form-control'}),
            'categoria': forms.Select(choices=choices, attrs={'class':'form-control'}),
        }
    
class CrearComentario(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['post','nombre', 'cuerpo']

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'cuerpo': forms.Textarea(attrs={'class':'form-control'}),

        }

TrabajoFinal/apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [ 
            'username', 
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username': 'Nombre de suario', 
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'email': 'Correo',
        }

TrabajoFinal/TrabajoFinal/views.py
from django.shortcuts import render


def nosotros(request):
	return render(request,"nosotros.html")

#def login(request):
#	return render(request,"login.html")

def base(request):
	return render(request,"base.html")

TrabajoFinal/apps/categorias/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.views.generic.detail import DetailView
from .models import Comentario, Redaccion
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import Formulario_Alta_Redaccion, CrearComentario
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, DeleteView
from django.views import generic
from .filters import RedaccionFiltro
# Create your views here.
#def Listar_Noticia(request):
 #   redaccion = Redaccion.objects.all()
 #   ctx = {}
 #   ctx['p'] = redaccion
 #   return render(request,'base.html', ctx)
#class filtroviews(generic.ListView):
#	queryset = Redaccion.objects.filter(estado=True)
#	templete_name= 'categorias/listar_noticias.html'

#def FiltroViews(request):
	#context = {}

	#filtro_redaccion = RedaccionFiltro(
		#request.GET,
		#queryset = Redaccion.objects.all()
	#)

	#context['filtro_redaccion'] = filtro_redaccion

	#return render(request ,'categorias/listar_noticias.html', context=context)

class Listar_Noticia(generic.ListView):
	model = Redaccion
	template_name = 'categorias/listar_noticias.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['filter'] = RedaccionFiltro(self.request.GET, queryset= self.get_queryset())
		return context


class RedactarNoticia(LoginRequiredMixin, CreateView):
	model = Redaccion
	form_class = Formulario_Alta_Redaccion
	template_name = 'nuevanoticia.html'
	success_url = reverse_lazy('categorias:noticias')



class DetalleArticulo(DetailView):
	model = Redaccion
	template_name = 'categorias/detalle_articulo.html'
	

class ComentarioViews(LoginRequiredMixin, CreateView):
	model = Comentario
	form_class = CrearComentario
	template_name = 'categorias/añadir_comentario.html'
	success_url = reverse_lazy('categorias:noticias')

	
class EditarRedaccion(LoginRequiredMixin ,UpdateView):
	model = Redaccion
	template_name = 'categorias/editar.html'
	fields = [ 'titulo', 'texto']
	success_url = reverse_lazy('categorias:noticias')

class EliminarRedaccion(LoginRequiredMixin ,DeleteView):
	model = Redaccion
	template_name = 'categorias/eliminar.html'
	success_url = reverse_lazy('categorias:noticias')
	

TrabajoFinal/apps/usuario/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm

#@login_required
#def noticia(request):
#	return render(request,"admi/nuevanoticia.html")

class RegistroUsuario(CreateView):
	model = User
	template_name = 'admi/registrar.html'
	form_class = RegistroForm
	success_url = reverse_lazy('base')

TrabajoFinal/templates/admi/registrar.html
{% extends 'base.html' %}
	
{% block content %}

<form class="formularioRegistro" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

TrabajoFinal/templates/base.html
<!DOCTYPE html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<html lang="en">
<title>operadores logicos</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

<style>
.w3-sidebar {
  z-index: 3;
  width: 250px;
  top: 43px;
  bottom: 0;
  height: inherit;
}
.formularioRegistro {
  margin-top: 50px;
}

.formularioRegistro2 {
  margin-top: 250px;
}


.modalEliminar {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 999;
  background-color: #fff;
  transform: translate(-50%,-50%);
  border-radius: 5px;
  border: 1px solid rgba(0,0,0,.2);
  padding-top: 16px;
  width: 500px;
}
.modalEliminar__header {
  padding-left: 16px;
  padding-right: 16px;
  padding-bottom: 16px;
  border-bottom: 1px solid rgba(0,0,0,.2);
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.modalEliminar__title {
  font-weight: 500;
  color: #212529;
  font-size: 20px;
}
.modalEliminar__btn-close {
  cursor: pointer;
  font-size: 30px;
  color: #212529;
}
.modalEliminar__btn-close:hover {
  opacity: 0.7;
  transition: all .3s;
}
.modalEliminar__body {
  padding: 16px;
  border-bottom: 1px solid rgba(0,0,0,.2);
}
.modalEliminar__body-text {
  color: #212529;
}
.modalEliminar__footer {
  padding: 16px;
  display: flex;
  justify-content: flex-end;
}
.modalEliminar__button {
  margin: 4px;
  padding: 6px 12px;
  border-radius: 4px;
  border: none;
  cursor: pointer;
  background-color: #6c757d;
  color: white;
}
.modalEliminar__button--cerrar:hover {
  background-color: #5c636a;
}
.modalEliminar__button--confirmar {
  background-color: #0d6efd;
}
.modalEliminar__button--confirmar:hover {
  background-color: #0b5ed7;
}
</style>
<body>

<!-- navegador -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <a href="{% url 'categorias:noticias' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Noticias</a>
    {% if user.is_authenticated %}
      <a href="{% url 'categorias:ver' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Crear Noticia</a>
      {% else %}
      <a href="{% url 'login' %}"></a>
    {% endif %}
    <a href="{% url 'nosotros' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Quienes somos</a>
    <a href="{% url 'base' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Condiciones de uso</a>
    {% if not user.is_authenticated %}
      <a href="{% url 'login' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Ingresar</a>
      {% else %}
      <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Salir</a>
      <span class="w3-bar-item"> Hola {{user.username}} </span>
    {% endif %}    
    </div>
</div>


{% block content %}
<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible 

<div class="w3-main" style="margin-left:250px">-->
<div class="w3-container w3-padding-64 w3-center" id="team">


  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal ">Somos una Web de novedades</h1>
      <p>lo mas importante para nosotros es poder compartir las noticias que todos necesitamos saber.</p>
    </div>
  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">   
  
</div>
<div class="w3-row">
<div class="w3-container">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal"> Condiciones de Uso </h1>
      <!--<h3> Condiciones de Uso:</h3>-->
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
       Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
       Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div class="w3-container w3-text-teal">
    <div class="w3-twothird w3-container">
    <h3><a href="{% url 'categorias:noticias' %}"> Ver las ultimas noticias⇒ </a></h2><br>
    </div>
    <br/><br/><br/>


{% endblock %}
  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4><span class="w3-xlarge w3-border-teal w3-bottombar">Operadores Logicos</h4>
    </div>
  </footer>

<!-- END MAIN -->
</div>
<!--<div class="modal fadel" id="eliminar" role="dialog">

</div>

{% block javascript %}
	<script>
  
  </script>
{% endblock %}-->

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

TrabajoFinal/templates/categorias/añadir_comentario.html
{% extends 'base.html' %}
	
	{% block content %}
      
      <h1> Nuevo comentario </h1>
     
        <div class="form-group">
<form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="" value="ENVIAR">
        </div>

  {% endblock content %}

TrabajoFinal/templates/categorias/detalle_articulo.html
{% extends 'base.html' %}
	
	{% block content %}
      
<div class="w3-row w3-padding-64">
   
      <h1 class="w3-text-teal ">

<h1>{{ redaccion.titulo }}</h1>
<small> Creado por {{ redaccion.autor.first_name }} {{ redaccion.autor.last_name }} </small><br/>
<hr>
<br/>
<div style="float: initial;" class="w3-twothird w3-container">
{{redaccion.texto}}
</div>
<br>
<br>
<small><a class="w3-text-teal" href="{% url 'categorias:editar' redaccion.pk %}"> (Editar publicación) </a></small><hr/>
<h2> Comentarios... </h2>
{% if not redaccion.comentarios.all %}
        No hay comentarios.. 
    {% else %}
        {% for comentario in redaccion.comentarios.all %}
    <hr>
    <strong>
        {{comentario.nombre}} -
        {{comentario.fecha_comentario}}
    </strong>
    <br/>
        {{comentario.cuerpo}}
        {% endfor %}
{% endif %}
<br/><br/>
 <a href="{% url 'categorias:nuevocoment' redaccion.pk %} "class="w3-text-teal">Has un nuevo comentario</a>
    
<br/><br/>
<button>
<a  href="{% url 'categorias:noticias' %}"> Volver a noticias </a>
</button>
 {% endblock content %}

TrabajoFinal/templates/categorias/editar.html
{% extends 'base.html' %}
	
	{% block content %}
      
      <h1> Editar Noticia </h1>
     
        <div class="form-group">
<form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="" value="Guardar">
        </div>

  {% endblock content %}

TrabajoFinal/templates/categorias/eliminar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
    .modalEliminar__button {
        margin: 4px;
        padding: 6px 12px;
        border-radius: 4px;
        border: none;
        cursor: pointer;
        background-color: #6c757d;
        color: white;
      }
      .modalEliminar__button--cerrar:hover {
        background-color: #5c636a;
      }
      .modalEliminar__button--confirmar {
        background-color: #0d6efd;
      }
      .modalEliminar__button--confirmar:hover {
        background-color: #0b5ed7;
      }

      .modalEliminar__btn-close:hover {
        opacity: 0.7;
        transition: all .3s;
      }
</style>
</head>
<body style="margin: 0; padding: 0;">
    <div style="width: 100vw; height: 100vh; background-color:#bdc3c7; display: flex; justify-content: center; align-items: center;">
        <form method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column;">
            {% csrf_token %}
            <h1 style="text-align:center; margin: 0; padding: 0;">¡¿Está seguro de que desea eliminar?!</h1><br><br>
            
            <div style="display: flex;">
                <button class="modalEliminar__button modalEliminar__btn--cerrar">
                    <a href="{% url 'categorias:noticias' %}" style="color: white; text-decoration: none;" type="submit">Cancelar</a>
                </button>
                <button class="modalEliminar__button modalEliminar__button--confirmar" type="submit">Confirmar</button>
            </div>
        </form>
    </div>
</body>
</html>


    

TrabajoFinal/templates/categorias/listar_noticias.html
   {% extends 'base.html' %}

	{% block content %}

    

      <!--{% if object_list %}
      <div class="w3-padding-64 w3-padding-large">
          <table>
            {% for redaccion in object_list %}
          <tr>
            <td><a class="w3-container w3-text-teal w3-twothird w3-container" href="{% url 'categorias:detallearticulo' redaccion.pk %}"> {{redaccion.titulo}} </a> Por: {{ redaccion.autor.first_name }} {{ redaccion.autor.last_name }}</td>
            <td>{{redaccion.fecha}}</td>
            <td>{{redaccion.categoria}}</td> 
          </tr>   
      {% endfor %}
      </table>
      {% else %}
      <h1>No hay registro</h1>
      {% endif %}-->
     <br/><br/>
     
      <form method="GET">
        Fecha: {{ filter.form.fecha }} Categoria: {{ filter.form.categoria }}
        <input type="submit" name="" value="buscar">
      </form>
      <div class="w3-padding-64 w3-padding-large">
      <table>
      {% for redaccion in filter.qs %}
        <tr>
          <td><a class="w3-container w3-text-teal w3-twothird w3-container" href="{% url 'categorias:detallearticulo' redaccion.pk %}"> {{ redaccion.titulo }} </a> Por: {{ redaccion.autor.first_name }} {{ redaccion.autor.last_name }}</td>
            <td><div class="w3-padding-large">{{redaccion.fecha}}</td>
            <td><div class="w3-padding-large">{{redaccion.categoria}} 
            <small><button><a href="{% url 'categorias:editar' redaccion.pk %}"> Editar </a></button></small>
            <small><button><a href="{% url 'categorias:eliminar' redaccion.pk %}"> Eliminar </a></button></small>
            </td></div>
          </tr>  
      </div>  
      {% endfor %}
      </table>
    </div>  
  </div>
  
  <!--<div class="modal fadel" id="eliminar" role="dialog"></div>-->

  

  <!--{% block javascript %}
	<script type="text/javascript">
    function abrir_modal_eliminar(url){
      const elementoEliminar = document.getElementById('eliminar')

      fetch(url)
        .then(response => response.text())
        .then(body => {
          elementoEliminar.innerHTML = body;
        })
    } 
 
  </script>
{% endblock %}-->
{% endblock content %}

TrabajoFinal/templates/login.html
{% extends 'base.html' %}
  
  {% block content %}
  
  <div class="w3-container w3-padding-64 w3-center" id="team">
  <div class="wrapper">
    
    <form class="login" method="POST">{%csrf_token%}
      {{form.errors}}
      <h1 class="w3-text-teal"> ¡¡Bienvenido al Blog!! </h1>
      <h4> Entra y contanos tus noticias</h4>
      <!--<p class="title">ingresar</p>-->
        <input type="text" name="username" placeholder="USUARIO"/>
        <i class="fa fa-user"></i>
        <input type="password" name="password" placeholder="PASSWORD"/><br/><br/>
        <i class="fa fa-key"></i>
        <a href="/usuario/registro">Registrarse</a>
        <input type="submit" name="" value="INGRESAR">
      </p>
    </form>
  </div>
  </div>
  {% endblock content %}

TrabajoFinal/templates/nosotros.html
{% extends 'base.html' %}
	
	{% block content %}
<div class="w3-container w3-padding-64 w3-center" id="team">
	<h2>Programadora</h2>
	<p>Esta pagina web fue creado por:</p>

	<div class="w3-row"><br>


		<div>
			<p style="text-align: center;">
	  		<img src="https://media-exp1.licdn.com/dms/image/C5603AQFcW7ehwLacAA/profile-displayphoto-shrink_800_800/0/1615152054016?e=1623283200&v=beta&t=RKip3FP-h8hqRT-d6Uz8fGMj7R882_fM453CisIHUQI" alt="Alumna" style="width: 150px;" class="w3-circle w3-hover-opacity">
	  		<h3>Rosmari Fernandez</h3>
			<a href="https://www.linkedin.com/in/rosmari-fernandez-0b35497a/" class="w3-text-teal"><p>Linkedin</p></a>
			<p>Programadora Back end</p>
			<p><small> Esta pagina esta echo con Python, Django y SQL Server</small></p>
			</p>
		</div>
	</div>
</div>

	{% endblock content %}

TrabajoFinal/templates/nuevanoticia.html
{% extends 'base.html' %}
	<!--aca el usuario va a poder subir sus noticias / novedades-->
	{% block content %}

<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

	<div class="w3-container w3-padding-64 w3-center" id="team">
		
		<div class="w3-col m7">
	      <form method="POST" enctype="multipart/form-date" class="w3-container w3-card-4 w3-padding-16 w3-white" target="_blank"> {% csrf_token %}
			{{form.as_p}}
	    	<input type="submit" name="enviar" value="Guardar">
	      </form>
	    
	    </div>
	</div>
</div>
	{% endblock content %}